name: TiMP_UPGRADE
services:
  server:
    build: .
    ports:
      - "44445:44444"
    volumes:
      - db_data_new:/app/data
    environment:
      - DB_PATH=/app/data/timp_new.db
    restart: unless-stopped

volumes:
  db_data_new: